/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lvnnqtsvjqcgrimjgrad"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2bm5xdHN2anFjZ3JpbWpncmFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0MDgyNTIsImV4cCI6MjA4ODk4NDI1Mn0.02V9hiNX_EG-o-wK8IlOK4U-hJE-E-N7B4L5Qe-aRik"